### PR TITLE
extracting data objects

### LINKED ISSUE #12: Extract JS Object data
Extract object data from .svelte files to a json file for simpler page updates

### PR DESCRIPTION
**Pull request by vaishnav-mk**
There's a `/data/data.json` file that you can update and both `ProjectList` and `Socials` files reflect the changes made to the json file. I couldn't find a way to streamline this process for logos and it currently requires you to specify it separately in the respective files

### CODE REVIEW

**Comment by Toeffe3** [comment]
Took me all morning but found a hack to implement variable path for images for this case.

**Review by Toeffe3 — CHANGES_REQUESTED** [review]
@vaishnav-mk 
I personally do not like the path: `data/data.js`, it is unnecessary maybe `content.js` would be better more descriptive name?

**Comment by Toeffe3** [comment]
@vaishnav-mk is this a Hacktober contribution? If so I'll make sure to add the tag for it to be accepted.

**Comment by vaishnav-mk** [comment]
I've completed hacktoberfest already and it's a simple contribution

**Review by Andreasgdp — CHANGES_REQUESTED** [review]
I agree with @Toeffe3 a bit, but maybe if you could create a .json file for each object type and use that instead of having it in a single `data/data.json`
Could look like this:
`data/projects.json`
`data/socials.json`
Seeing as the projects and socials are unrelated.

**Comment by vaishnav-mk** [comment]
Sure, thanks for your input, I'll try to make the changes accordingly!

**Comment by vaishnav-mk** [comment]
Let me know if these changes suit your needs

**Review by Toeffe3 — APPROVED** [review]

**Review by Andreasgdp — APPROVED** [review]

**Pull request merged**
